[package]
name = "Axum_tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }

serde = "1.0.215"
serde_json = "1.0.133"
axum = "0.6"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.10"